DELIMITER $$
CREATE PROCEDURE sp_create_tracker()
BEGIN
    CREATE TABLE IF NOT EXISTS tracker (
        id INT AUTO_INCREMENT PRIMARY KEY,
        ticket_number VARCHAR(50) NOT NULL,
        site_id VARCHAR(50),
        site_name VARCHAR(150),
        ticket_status_name VARCHAR(100),
        regional VARCHAR(100),
        network_operation_and_productivity VARCHAR(150),
        teritory_operation VARCHAR(150),
        workable_status VARCHAR(50),
        general_status TEXT,
        asset_status VARCHAR(50),
        ticket_summary TEXT,
        ticket_batch VARCHAR(50),
        ticket_sub_type_name VARCHAR(100),
        ticket_created_date DATETIME,
        jumlah_asset INT DEFAULT 0,
        cat_asset VARCHAR(50),
        asset_position VARCHAR(50),
        percentage_asset_actual INT NOT NULL,
        plan_asset_dismantle TEXT,
        actual_asset_dismantle VARCHAR(100),
        assignee_group VARCHAR(150),
        tp_company VARCHAR(100),
        latitude DECIMAL(10,6),
        longitude DECIMAL(10,6),
        caf_status VARCHAR(50),
        working_permit_start_date DATETIME,
        working_permit_end_date DATETIME,
        working_permit_status_name VARCHAR(100),
        start_permit_tp_date DATE,
        end_permit_tp_date DATE,
        status_permit_tp VARCHAR(50),
        site_status VARCHAR(100),
        site_issue VARCHAR(100),
        category_issue VARCHAR(100),
        detail_issue VARCHAR(255),
        remark_dismantle TEXT,
        mom TEXT,
        cat_pending_approval VARCHAR(50),
        aging_pending_approval INT,
        submit_before DATETIME,
        approve_before DATETIME,
        dismantle VARCHAR(50),
        submit_after VARCHAR(50),
        approve_after VARCHAR(50),
        pcaa_approve DATETIME,
        closed DATETIME,
        partner_company VARCHAR(100),
        plan_dismantle_date DATE,
        plan_dismantle_week VARCHAR(10),
        pic_team VARCHAR(100),
        no_handphone BIGINT
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
END$$
DELIMITER ;